# Generated by Django 4.2.2 on 2023-07-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Fvector-art%2F4312696-food-logo-template-design-vector-icon-illustration&psig=AOvVaw2Q3nRVsavtn1g_DoXfAqRe&ust=1690588858187000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCODYq7WMsIADFQAAAAAdAAAAABAE",
                max_length=500,
            ),
        ),
    ]
