# Generated by Django 4.2.2 on 2023-07-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(default="", max_length=500),
        ),
    ]
